### ISSUE TITLE
Redesign the API with tickets in mind

### ISSUE THREAD

**Issue by KOLANICH** [DNedic/lfbb_cpp#1]
>Pair containing the pointer to the beginning of the area and elements available

I guess it should be `std::span`.

**Comment by DNedic** [comment]
Thanks for the suggestion! Unfortunately ```std::span``` requires C++20 and one of the goals of this library was to keep the compiler and standard requirements low so that it's embedded and systems friendly.

Also it would be a breaking change, which is also not very nice.

I will think about the suggestion some more, but for now I am closing the issue.

**Comment by KOLANICH** [comment]
>requires C++20 and one of the goals of this library was to keep the compiler and standard requirements low

One can check C++ version with a preprocessor.

**Comment by DNedic** [comment]
> One can check C++ version with a preprocessor.

True, and this is fine for changing the internals. But changing the API based on the C++ version is not.

The issue here is that people access ```first``` and ```second``` members of ```std::pair``` or use the ```get()``` method. Neither of these are available with ```std::span```.

**Comment by KOLANICH** [comment]
Yes, you cannot change the existing API, but you can add additional API based on the version. Or an alternative can be to just drop non-span API in a major version and use polyfills (and expect them to be installed systemwide) for older C++ versions (which one to use can be controlled by a macrodef or maybe by a template parameter).

**Comment by DNedic** [comment]
> Yes, you cannot change the existing API, but you can add additional API based on the version. 

Good suggestion, If you have the time feel free to open a PR for adding the additional API. Otherwise I will experiment with this and add it when I have the time.

> Or an alternative can be to just drop non-span API in a major version and use polyfills (and expect them to be installed systemwide) for older C++ versions (which one to use can be controlled by a macrodef or maybe by a template parameter).

Could you elaborate on the polyfills part? Would this be achievable on bare metal embedded systems?

**Comment by KOLANICH** [comment]
Polyfills are usually header-only libs like [`nonstd::span`](https://raw.githubusercontent.com/martinmoene/span-lite/master/include/nonstd/span.hpp) or [`tcb::span`](https://raw.githubusercontent.com/tcbrindle/span/master/include/tcb/span.hpp). 

I haven't tested them on embedded systems. But I remember I was successfully using some other C++20 libs (`magic_enum`) on Arduino (though I haven't used `span`s on Arduino at all, and bringing modern C++ to Arduino required some tinkering with Clang + some patches to AVR and Arduino standard libs + some patches to CMake toolchain files).

**Comment by DNedic** [comment]
> Polyfills are usually header-only libs like [`nonstd::span`](https://raw.githubusercontent.com/martinmoene/span-lite/master/include/nonstd/span.hpp) or [`tcb::span`](https://raw.githubusercontent.com/tcbrindle/span/master/include/tcb/span.hpp).
> 
> I haven't tested them on embedded systems. But I remember I was successfully using some other C++20 libs (`magic_enum`) on Arduino (though I haven't used `span`s on Arduino at all, and bringing modern C++ to Arduino required some tinkering with Clang + some patches to AVR and Arduino standard libs + some patches to CMake toolchain files).

I will look into this for the future, but it's going to be some time in the future if I decide to take that route. In the meantime, I am open to extending the API for C++20.
